#!/bin/sh

sudo fallocate -l 1GiB /mnt/Cache/Swap
sudo chmod 600 /mnt/Cache/Swap
sudo mkswap /mnt/Cache/Swap

#sudo bash -c "echo \"/mnt/Cache/Swap swap swap defaults 0 0\" >> /etc/fstab"

cat /proc/sys/vm/swappiness
sudo sysctl vm.swappiness=10
cat /proc/sys/vm/swappiness

#sudo bash -c "echo \"vm.swappiness=10\" >> /etc/sysctl.conf"
