#!/bin/sh

sudo fallocate -l 1GiB /Swap
sudo chmod 600 /Swap
sudo mkswap /Swap

sudo swapon /Swap
sudo swapon --show

#sudo bash -c "echo \"/Swap swap swap defaults 0 0\" >> /etc/fstab"

cat /proc/sys/vm/swappiness
sudo sysctl vm.swappiness=10
cat /proc/sys/vm/swappiness

#sudo bash -c "echo \"vm.swappiness=10\" >> /etc/sysctl.conf"
