#!/bin/sh

# RCon Save-Off
~/Minecraft/Scripts/RemoteConsole/rcon-cli save-off

# RCon Save-All
~/Minecraft/Scripts/RemoteConsole/rcon-cli save-all

# Copy RAM Disk To Cache Disk
cp -r /mnt/TmpFS/ /mnt/Cache/$(date +%H%M)/

# Replace Storage With RAM Disk
rm -rf /mnt/Storage/TmpFS/
cp -r /mnt/TmpFS/ /mnt/Storage/TmpFS/
rm -rf /mnt/Storage/SignificantBrothers/
cp -r /mnt/Storage/TmpFS/ /mnt/Storage/SignificantBrothers/

# RCon Save-On
~/Minecraft/Scripts/RemoteConsole/rcon-cli save-on
