#!/bin/sh

sudo mkfs.ext4 -m 0 -E lazy_itable_init=0,lazy_journal_init=0,discard /dev/disk/by-id/google-transport0

sudo mkdir /mnt/Transport/

sudo mount -o discard,defaults /dev/disk/by-id/google-transport0 /mnt/Transport/

sudo chmod a+w /mnt/Transport/

#bash -c "echo \"UUID=`sudo blkid -s UUID -o value /dev/disk/by-id/google-storage0` /mnt/Storage ext4 discard,defaults,nofail 0 2\" >> /etc/fstab"
