#!/bin/sh

cd ~/Minecraft/Environments/SignificantBrothers

# Update Server Properties
cat ./ServerProperties ./1P > ./server.properties

# Start Minecraft Server
java -jar ~/Minecraft/Servers/Vanilla/Server.jar --nogui --bonusChest --universe ~/Minecraft/RAMDisk/ --world SignificantBrothers
