#!/bin/sh
./Scripts/PHPServer
cd Environments/SignificantBrothers/
java -Xmx3072M -Xms3072M -jar ../../Servers/Vanilla/Server.jar --nogui --bonusChest --universe ../../Worlds/ --world SignificantBrothers
../../Scripts/AddCommitPush
