#!/bin/sh

echo "\n\nUpdating Package Lists :\n"
echo "$ sudo apt-get --assume-yes update\n"
sudo apt-get --assume-yes update

echo "\n\nUpdating Packages :\n"
echo "$ sudo apt-get --assume-yes dist-upgrade\n"
sudo apt-get --assume-yes dist-upgrade

echo "\n\nInstalling Utilities :\n"
echo "$ sudo apt-get --assume-yes install git htop less speedtest-cli\n"
sudo apt-get --assume-yes install git htop less speedtest-cli

echo "\n\nInstalling Dependencies :\n"
echo "$ sudo apt-get --assume-yes install default-jdk\n"
sudo apt-get --assume-yes install default-jdk

echo "\n\nCreating User Folder :\n"
echo "$ mkdir ~/.Minecraft/"
mkdir ~/.Minecraft/

echo "\n\nInstalling Environments :\n"
echo "$ cp -r ~/Minecraft/Environments/ ~/.Minecraft/Environments/"
cp -r ~/Minecraft/Environments/ ~/.Minecraft/Environments/

#echo "\n\nDownloading Vanilla Minecraft Server :\n"
#echo "$ curl -O https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar\n"
#curl -O https://launcher.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar
#echo "\n\nCreating EULA File :\n"
#echo "$ echo \"eula=true\" > ./eula.txt\n"
#echo "eula=true" > ./eula.txt
#echo "\n\nCreating Server Properties File :\n"
#echo "$ touch ./server.properties\n"
#touch ./server.properties
#echo "\n\nInitializing Minecraft Server :\n"
#echo "$ java -jar ./server.jar --nogui --initSettings\n"
#java -jar ./server.jar --nogui --initSettings
#echo "\n\nReviewing Server Properties File :\n"
#echo "$ nano ./server.properties\n"
#nano ./server.properties
#echo "\n\nCreating Help Script :\n"
#echo "$ echo \"#!/bin/sh\\\ncd $(pwd)\\\nexec java -jar $(pwd)/server.jar --nogui --help\" > ./Help\n"
#echo "$ chmod +x ./Help\n"
#echo "#!/bin/sh\ncd $(pwd)\nexec java -jar $(pwd)/server.jar --nogui --help" > ./Help
#chmod +x ./Help
#echo "\n\nCreating Start Script :\n"
#echo "$ echo \"#!/bin/sh\\\ncd $(pwd)\\\nexec java -Xmx2048M -Xms2048M -jar $(pwd)/server.jar --nogui --bonusChest\" > ./Start\n"
#echo "$ chmod +x ./Start\n"
#echo "#!/bin/sh\ncd $(pwd)\nexec java -Xmx2048M -Xms2048M -jar $(pwd)/server.jar --nogui --bonusChest" > ./Start
#chmod +x ./Start

echo "\n\nListing Directory Contents :\n"
echo "$ ls -la ./\n"
ls -la ./

echo "\n\nInstallation Complete\n\n"
